apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
      serviceAccountName: prometheus
      initContainers:
      - name: "init-chown-data"
        image: "busybox"
        # 1000 is the user that prometheus uses.
        command: ["chown", "-R", "1000:2000", /prometheus]
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.37.1
        args:
          - '--storage.tsdb.path=/prometheus'
          - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
          - containerPort: 9090
            name: http-prometheus
            protocol: TCP
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus
        - name: prometheus-storage-volume
          mountPath: /prometheus
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 250m
            memory: 750Mi
      restartPolicy: Always
      volumes:
      - name: prometheus-config-volume
        configMap:
            defaultMode: 420
            name: prometheus-config
      - name: prometheus-storage-volume
        persistentVolumeClaim:
            claimName: prometheus-pvc
