apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{.Values.env}}
type: Opaque
data:
  # Encode your secret in base64
  # Do not put your secret here if is not encode in base64
  POSTGRES_DB: {{.Values.secret.dbName}}
  POSTGRES_USER: {{.Values.secret.dbUser}}
  POSTGRES_PASSWORD: {{.Values.secret.dbPassword}}
