apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{.Values.env}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: 5432
      protocol: TCP
      name: postgres
