apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: http-interface
spec:
  hosts:
  - s42.app
  gateways:
  - s42-app-live

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface
spec:
  selector: {}
  template:
    spec:
      containers:
      - name: interface
        env:
        - name: NEXT_PUBLIC_GRAPHQL_API
          value: https://s42.app/graphql
        - name: NEXTAUTH_URL
          value: https://s42.app