// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/google/uuid"
)

type Cluster struct {
	ID uuid.UUID `json:"id"`
}

type DuoCampus struct {
	ID uuid.UUID `json:"id"`
}

type Friendship struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"userID"`
	User     *User     `json:"user"`
	FriendID uuid.UUID `json:"friendID"`
	Friend   *User     `json:"friend"`
}

type Group struct {
	ID     uuid.UUID `json:"id"`
	User   *User     `json:"user"`
	UserID uuid.UUID `json:"userID"`
	Name   string    `json:"name"`
	Color  *string   `json:"color"`
}

type Hello struct {
	Name string `json:"name"`
}

type Location struct {
	ID uuid.UUID `json:"id"`
}

type OmniauthAccount struct {
	ID       uuid.UUID `json:"id"`
	User     *User     `json:"user"`
	UserID   uuid.UUID `json:"userID"`
	Provider string    `json:"provider"`
	UID      string    `json:"uid"`
	Username *string   `json:"username"`
	Email    *string   `json:"email"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	DuoLogin       string    `json:"duoLogin"`
	DuoID          int       `json:"duoID"`
	FirstName      string    `json:"firstName"`
	UsualFirstName *string   `json:"usualFirstName"`
	LastName       string    `json:"lastName"`
	Phone          *string   `json:"Phone"`
	PoolYear       *int      `json:"PoolYear"`
	PoolMonth      *int      `json:"PoolMonth"`
	Nickname       *string   `json:"Nickname"`
	AvatarURL      *string   `json:"AvatarURL"`
	CoverURL       *string   `json:"CoverURL"`
}

type Workspace struct {
	ID uuid.UUID `json:"id"`
}
