apiVersion: batch/v1
kind: CronJob
metadata:
  name: campus-crawler
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: service
            env:
            - name: DEBUG
              value: 'true'
            - name: DATABASE_HOST
              value: next-primary-postgres