export const countryNameToEmoji: { [key: string]: string } = {
  Turkey: '🇹🇷',
  Switzerland: '🇨🇭',
  Italy: '🇮🇹',
  Luxembourg: '🇱🇺',
  'Czech Republic': '🇨🇿',
  Armenia: '🇦🇲',
  'Russian Federation': '🇷🇺',
  'United Kingdom': '🇬🇧',
  Netherlands: '🇳🇱',
  Romania: '🇷🇴',
  Brazil: '🇧🇷',
  Jordan: '🇯🇴',
  Austria: '🇦🇹',
  Australia: '🇦🇺',
  Germany: '🇩🇪',
  Canada: '🇨🇦',
  Finland: '🇫🇮',
  Portugal: '🇵🇹',
  Ukraine: '🇺🇦',
  'Moldova, Republic of': '🇲🇩',
  Spain: '🇪🇸',
  'United Arab Emirates': '🇦🇪',
  Belgium: '🇧🇪',
  Morocco: '🇲🇦',
  France: '🇫🇷',
  'Korea, Republic of': '🇰🇷',
  'South Africa': '🇿🇦',
  Malaysia: '🇲🇾',
  Japan: '🇯🇵',
  Thailand: '🇹🇭',
  'United States': '🇺🇸',
};
