auth_enabled: false
common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /data/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: loki_
        period: 24h
limits_config:
  retention_period: 336h
  retention_stream:
    - selector: '{namespace="sandbox"}'
      priority: 1
      period: 24h
    - selector: '{namespace="previews"}'
      priority: 1
      period: 24h
memberlist:
  join_members:
    - "loki"
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
storage_config:
  filesystem:
    directory: /data/loki/chunks
