server:
  http_listen_port: 3100
storage:
  trace:
    backend: local
    local:
      path: /data/traces
    wal:
      path: /data/wal
overrides:
  per_tenant_override_config: /etc/tempo/overrides.yaml
