apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: next-s42-app
  namespace: istio-system
spec:
  dnsNames:
    - next.s42.app
    - '*.next.s42.app'
  issuerRef:
    kind: ClusterIssuer
    name: ovh-issuer
  secretName: next-s42-app-tls
