---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cinder-classic
  resources:
    requests:
      storage: 10Gi
