apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-stud42-dev
  namespace: dev
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "stud42-dev-cert"
      hosts:
        - "dev.stud42.atomys.app"
