apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector: {}
  template:
    spec:
      containers:
      - name: service
        env:
        - name: DEBUG
          value: 'true'
        - name: DATABASE_HOST
          value: sand-primary-postgres