apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: next-
resources:
- ../../base
namespace: staging
images:
- name: app
  newName: ghcr.io/42atomys/stud42
  newTag: latest

patchesStrategicMerge:
- ./use-next-primary-postgres.yaml
- ./use-next-routing.yaml
- ./use-next-resources.yaml

replacements:
- source:
    kind: Service
    name: http-api
    fieldPath: metadata.name
  targets:
  - select:
      kind: VirtualService
      name: http-api
    fieldPaths:
     - spec.http.*.name
     - spec.http.*.route.*.destination.host
- source:
    kind: Deployment
    fieldPath: metadata.labels.[app.kubernetes.io/version]
  targets:
  - select:
      kind: Deployment
    fieldPaths:
     - spec.template.spec.containers.[name=service].env.[name=APP_VERSION].value