apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - name: service
        resources:
          limits:
            memory: "100Mi"
            cpu: "150m"