# apiVersion: v1
# kind: Service
# metadata:
#   name: grpc-jwtks-service
# spec:
#   ports:
#   - name: grpc-jwtks-service
#     port: 5000
#     targetPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: http-jwtks-service
# spec:
#   ports:
#   - name: http-jwtks-service
#     port: 5500
# targetPort: 5500
