# API relatives configurations
api: {}

# Interface relatives configurations
interface: {}

# jwtks service relatives configurations
jwtks:
  jwk:
    cert_private_key: /etc/stud42/certs/private.key
    cert_public_key: /etc/stud42/certs/public.pem
  grpc:
    cert_private_key: /etc/stud42/certs/server.key
    cert_public_key: /etc/stud42/certs/server.pem