apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
resources:
  - ../../base
namespace: production
images:
  - name: app
    newName: ghcr.io/42atomys/stud42
    newTag: latest

patchesStrategicMerge:
  - ./use-live-routing.yaml

replacements:
  - source:
      kind: Service
      name: grpc-jwtks-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: Certificate
          name: jwtks-service
        fieldPaths:
          - spec.dnsNames.0
  - source:
      kind: Service
      name: http-jwtks-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: VirtualService
          name: http-jwtks-service
        fieldPaths:
          - spec.http.*.name
          - spec.http.*.route.*.destination.host
