# Allowed env: dev, staging, prod
env: dev

image:
  repository: postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

service:
  type: ClusterIP
  port: 5432

storage:
  # Available storage class on OVH
  # SSD: cinder-hish-speed csi-cinder-high-speed
  # HDD: cinder-classic csi-cinder-classic
  storageClassName: csi-cinder-classic
  size: "10Gi"

secret:
  # Encode your secret in base64
  # Do not put your secret here if is not encode in base64
  dbName: 
  dbUser: 
  dbPassword: 