// DO NOT EDIT THIS FILE MANUALLY - IT IS GENERATED FROM THE CONTENT OF THE CAMPUS FOLDER
// RUN `yarn generate:campus` TO REGENERATE IT

import { CampusIdentifier, ICampus } from './types';
import { Helsinki } from './campus/helsinki';
import { Lausanne } from './campus/lausanne';
import { Malaga } from './campus/malaga';
import { Mulhouse } from './campus/mulhouse';
import { Paris } from './campus/paris';
import { SaoPaulo } from './campus/saoPaulo';
import { Seoul } from './campus/seoul';
import { Tokyo } from './campus/tokyo';
import { Vienna } from './campus/vienna';
import { Wolfsburg } from './campus/wolfsburg';

export const Campuses: Record<CampusIdentifier, ICampus> = {
  helsinki: new Helsinki(),
  lausanne: new Lausanne(),
  malaga: new Malaga(),
  mulhouse: new Mulhouse(),
  paris: new Paris(),
  saoPaulo: new SaoPaulo(),
  seoul: new Seoul(),
  tokyo: new Tokyo(),
  vienna: new Vienna(),
  wolfsburg: new Wolfsburg(),
};
