// DO NOT EDIT THIS FILE MANUALLY - IT IS GENERATED FROM THE CONTENT OF THE CAMPUS FOLDER
// RUN `yarn generate:campus` TO REGENERATE IT

/**
 * List of all campus names present in the interface as their identifier.
 * Identifier must be in camelCase without spaces or special characters. It
 * must be unique in the list.
 */
export type CampusIdentifier =
  | 'helsinki'
  | 'lausanne'
  | 'malaga'
  | 'mulhouse'
  | 'paris'
  | 'saoPaulo'
  | 'seoul'
  | 'tokyo'
  | 'vienna'
  | 'wolfsburg';

/**
 * CampusLink is the same as CampusIdentifier but with a dash between words.
 * It is used for links in the interface. It is the same as CampusIdentifier
 * but in kebab-case instead of camelCase generated by the type.
 */
export type CampusLink =
  | 'helsinki'
  | 'lausanne'
  | 'malaga'
  | 'mulhouse'
  | 'paris'
  | 'saopaulo'
  | 'seoul'
  | 'tokyo'
  | 'vienna'
  | 'wolfsburg';
