// DO NOT EDIT THIS FILE MANUALLY - IT IS GENERATED FROM THE CONTENT OF THE CAMPUS FOLDER
// RUN `yarn generate:campus` TO REGENERATE IT

/**
 * List of all campus names present in the interface as their identifier.
 * Identifier must be in camelCase without spaces or special characters. It
 * must be unique in the list.
 */
export type CampusIdentifier =
  | 'angouleme'
  | 'helsinki'
  | 'lausanne'
  | 'lyon'
  | 'madrid'
  | 'malaga'
  | 'mulhouse'
  | 'paris'
  | 'saoPaulo'
  | 'seoul'
  | 'tokyo'
  | 'urduliz'
  | 'vienna'
  | 'wolfsburg';
