resources:
- ../../base

namespace: production

patches:
- target:
    kind: PersistentVolumeClaim
    name: primary-postgres
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: 10Gi