---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  # Encode your secret in base64
  # Do not put your secret here if is not encode in base64
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
