# Configuration Map for deployment.yaml
# Edit it to change the configuration of your proxy
# Don't forget to restart your proxy after changing it
#
# Path: examples/kubernetes/deployment.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhooked
data:
  webhooks.yaml: |
    apiVersion: v1alpha1
    observability:
      metricsEnabled: true
    specs:
    - name: users-create
      entrypointUrl: /users/create
      security:
      - header:
          inputs:
          - name: headerName
            value: X-Secret
      - compare:
          inputs:
          - name: first
            value: '{{ .Outputs.header.value }}'
          - name: second
            valueFrom:
              envRef: WEBHOOK_SECRET_HEADER
      storage: []
    - name: users-update
      entrypointUrl: /users/update
      security:
      - header:
          inputs:
          - name: headerName
            value: X-Secret
      - compare:
          inputs:
          - name: first
            value: '{{ .Outputs.header.value }}'
          - name: second
            valueFrom:
              envRef: WEBHOOK_SECRET_HEADER
      storage: []
    - name: locations-create
      entrypointUrl: /locations/create
      security:
      - header:
          inputs:
          - name: headerName
            value: X-Secret
      - compare:
          inputs:
          - name: first
            value: '{{ .Outputs.header.value }}'
          - name: second
            valueFrom:
              envRef: WEBHOOK_SECRET_HEADER
      storage: []
    - name: locations-close
      entrypointUrl: /locations/close
      security:
      - header:
          inputs:
          - name: headerName
            value: X-Secret
      - compare:
          inputs:
          - name: first
            value: '{{ .Outputs.header.value }}'
          - name: second
            valueFrom:
              envRef: WEBHOOK_SECRET_HEADER
      storage: []
    - name: locations-destroy
      entrypointUrl: /locations/destroy
      security:
      - header:
          inputs:
          - name: headerName
            value: X-Secret
      - compare:
          inputs:
          - name: first
            value: '{{ .Outputs.header.value }}'
          - name: second
            valueFrom:
              envRef: WEBHOOK_SECRET_HEADER
      storage: []