apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwtks-service
spec:
  selector: {}
  revisionHistoryLimit: 1
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-creds
      containers:
      - name: service
        image: app
        args: [ '--config', '/config/stud42.yaml', serve, jwtks ]
        command: [ stud42cli ]
        env:
        - name: GO_ENV
          value: review-apps
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: 'JWTKS_SERVICE_DSN'
              name: 'sentry-dsns'
        volumeMounts:
          - name: certs-grpc
            mountPath: '/etc/certs/grpc'
            readOnly: true
          - name: certs-jwk
            mountPath: '/etc/certs/jwk'
            readOnly: true
          - name: config
            mountPath: /config
            readOnly: true
        resources:
          limits:
            memory: "42Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
        - containerPort: 5500
      volumes:
      - name: certs-grpc
        secret:
          secretName: jwtks-service-tls
      - name: certs-jwk
        secret:
          secretName: jwtks-service-jwk-tls
      - name: config
        configMap:
          name: stud42-config