apiVersion: v1
kind: Service
metadata:
  name: jwtks-service-grpc
spec:
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: jwtks-service-http
spec:
  ports:
  - port: 5500
    targetPort: 5500