apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tempo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cinder-classic
  resources:
    requests:
      storage: 10Gi
