apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/name: tempo
