---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-promtail
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: "2.6.1"
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - watch
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-promtail
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: "2.6.1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-promtail
subjects:
  - kind: ServiceAccount
    name: loki-promtail
    namespace: monitoring

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-promtail
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: "2.6.1"
