apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-http
spec:
  hosts:
  - s42.app
  gateways:
  - s42-app
  http:
  - name: api-http-gql
    match:
    - method:
        exact: POST
      uri:
        exact: "/graphql"
    rewrite:
      uri: "/graphql"
    route:
    - destination:
        host: api-http
        port:
          number: 4000
  - name: api-http-gqli
    match:
    - method:
        exact: GET
      uri:
        exact: "/graphql"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: api-http
        port:
          number: 4000