apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-postgres
spec:
  selector: {}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: postgres:14.1-alpine3.14
        imagePullPolicy: IfNotPresent
        name: postgres
        resources:
          requests:
            cpu: "250m"
            memory: "500Mi"
          limits:
            cpu: "250m"
            memory: "500Mi"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: primary-postgres-credentials
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: primary-postgres
      restartPolicy: Always
