apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
resources:
- ../../base
namespace: staging
images:
- name: app
  newName: ghcr.io/42atomys/stud42
  newTag: latest

patches:
- target:
    kind: Deployment
    name: api
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: prod-primary-postgres

replacements:
- source:
    kind: Service
    name: api-http
    fieldPath: metadata.name
  targets:
  - select:
      kind: VirtualService
      name: api-http
    fieldPaths:
     - spec.http.*.name
     - spec.http.*.route.*.destination.host