apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: http-api
spec:
  hosts:
  - s42.app
  gateways:
  - s42-app-live

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector: {}
  template:
    spec:
      containers:
      - name: service
        env:
        - name: CORS_ORIGIN
          value: https://s42.app