name: Tests - Backend 💻
on: 
  pull_request:
    paths-ignore:
    - '.github/**'
    - 'web/ui/**'
    - 'docs/**'
    - 'deploy/**'
  push:
    branches:
      - main
    paths-ignore:
    - '.github/**'
    - 'web/ui/**'
    - 'docs/**'
    - 'deploy/**'

jobs:
  linters:
    name: Backend Linters 💻
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
    - name: Generate code
      run: make -f build/Makefile deps generate
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        version: latest

  tests:
    name: Backend Tests 💻
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
    - name: Generate code
      run: make -f build/Makefile deps generate
    - name: Run Unit tests
      run: |
        go test ./... -coverprofile coverage.out -covermode count
        go tool cover -func coverage.out
    - name: Quality Gate - Test coverage shall be above threshold
      # continue-on-error to allow job to pass without tests.
      # @see issue #57 on Github
      continue-on-error: true
      env:
          TESTCOVERAGE_THRESHOLD: 80
      run: |
        echo "Quality Gate: checking test coverage is above threshold ..."
        echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
        totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
        echo "Current test coverage : $totalCoverage %"
        if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
            echo "OK"
        else
            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
            echo "Failed"
            exit 1
        fi
    - name: Run Go Build
      run: |
        go build -o /tmp/applications-test-units