name: CI/CD 🚀
on:
  pull_request:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ###############################
  ########### LINTERS ###########
  ###############################
  linters:
    name: "Linters 🧹"
    uses: ./.github/workflows/linters.yaml
  ###############################
  ############ TESTS ############
  ###############################
  tests:
    name: Tests 🧪
    uses: ./.github/workflows/tests.yaml
    with:
      environment: ${{ github.event_name == 'pull_request' && 'review-apps' || 'sandbox' }}
  ###############################
  ############ BUILD ############
  ###############################
  build:
    name: "Build 🔧"
    needs: [tests]
    uses: ./.github/workflows/build.yaml
    with:
      environment: ${{ github.event_name == 'pull_request' && 'review-apps' || 'sandbox' }}
  ###############################
  ########### DEPLOY ############
  ###############################
  deploy:
    name: "Deploy 🚀"
    needs: [build]
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: ${{ github.event_name == 'pull_request' && 'review-apps' || 'sandbox' }}
