name: CI/CD 🚀
on:
  release:
    types: [prereleased, released]
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ###############################
  ########### LINTERS ###########
  ###############################
  # linters:
  #   name: "Linters 🧹"
  #   uses: ./.github/workflows/linters.yaml
  ###############################
  ############ TESTS ############
  ###############################
  # tests:
  #   name: Tests 🧪
  #   uses: ./.github/workflows/tests.yaml
  #   secrets: inherit
  ###############################
  ############ BUILD ############
  ###############################
  # build:
  #   name: "Build 🔧"
  #   needs: [linters, tests]
  #   uses: ./.github/workflows/build.yaml
  ###############################
  ########### DEPLOY ############
  ###############################

  deploy:
    name: "Deploy 🚀"
    # needs:  [tests, linters, build]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environmentName: "${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || (github.event_name == 'release' && github.event.action == 'released' && 'production' || 'staging') }}"
      stacks: '["test"]'
      image: "false" # ${{ needs.build.outputs.image }}
