name: CI/CD 🚀
on:
  release:
    types: [prereleased, released]
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ###############################
  ########### LINTERS ###########
  ###############################
  linters:
    name: "Linters 🧹"
    uses: ./.github/workflows/linters.yaml
  ###############################
  ############ TESTS ############
  ###############################
  tests:
    name: Tests 🧪
    uses: ./.github/workflows/tests.yaml
    secrets: inherit
  ###############################
  ############ BUILD ############
  ###############################
  build:
    name: "Build 🔧"
    needs: [linters, tests]
    uses: ./.github/workflows/build.yaml
  ###############################
  ########### DEPLOY ############
  ###############################
  deploy:
    name: "Deploy 🚀"
    needs: [build]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    if: github.event_name == 'release' || github.event_name == 'pull_request'
    with:
      environmentName: ${{ github.event_name == 'pull_request' && "reviews/${{ github.ref_name }}" || 'sandbox' }}
      stacks: '["test"]'
      image: ${{ needs.build.outputs.image }}
