name: 'Deployer 🔧'
on:
  pull_request: 
    branches:
    - main
  push:
    branches:
    - main
  release:
    types:
    - prereleased
    - published
jobs:
  build_and_push:
    name: 'Build & push to ghcr.io 🔧'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        github-token: ${{ github.token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: build/Dockerfile

  deploy_next:
    name: Deploy to next 🎉
    runs-on: ubuntu-latest
    needs: [ build_and_push ]
    if: ${{ github.event.release.action == 'prereleased' }}
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-kubectl@v2.0
    - uses: imranismail/setup-kustomize@v1
    - uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_ADMIN }}
        cluster-type: generic
    - run: |
        cd deploy/app/jwkts-service/overlays/next
        kustomize edit set image app=ghcr.io/42atomys/stud42:${{ github.event.release.tag_name }}
        kustomize build . | kubectl apply -f -

  deploy_live:
    name: Deploy to live 🚀
    runs-on: ubuntu-latest
    needs: [ build_and_push, deploy_next ]
    if: ${{ github.event.release.action == "released" }}
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-kubectl@v2.0
    - uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_ADMIN }}
        cluster-type: generic
    - run: |
        cd deploy/app/jwkts-service/overlays/live
        kustomize edit set image app=ghcr.io/42atomys/stud42:${{ github.event.release.tag_name }}
        kustomize build . | kubectl apply -f -