apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: s42-app-next
  namespace: staging
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: next-s42-app-tls
      hosts:
        - "next.s42.app"
        - "*.next.s42.app"