apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: s42-monitoring
  namespace: monitoring
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: s42-app-tls
      hosts:
      - "dashboards.s42.app"